### ISSUE TITLE
Error: read EIO

### ISSUE THREAD

**Issue by BenNG** [grncdr/npm-exec#4]
Command run successfully but at the end I have always this error

```
stream.js:94
      throw er; // Unhandled stream error in pipe.
            ^
Error: read EIO
    at errnoException (net.js:901:11)
    at TTY.onread (net.js:556:19)
```

**Comment by acarl005** [comment]
Same error. Commands are all fine but this shows up at the end. Running node 4.0.0 on Ubuntu 15.04.

```
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: read EIO
    at exports._errnoException (util.js:837:11)
    at TTY.onread (net.js:544:26)
```

**Comment by amberkhare** [comment]
Getting same error after installing Node and trying to run node.exe

> events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: read EINVAL
    at exports._errnoException (util.js:870:11)
    at TTY.onread (net.js:552:26)

Can someone please help.

**Comment by adekola** [comment]
Hi everyone, I'm having a similar issue but within an example code for Wit.ai 

Seems to be a common nodejs problem. has anyone found a fix?
